export const PRIMARY_MODELS = [
  { id: 'speech-2.8-hd', name: 'Speech 2.8 HD', description: '官方最新高音质模型，音色细节更强' },
  { id: 'speech-2.8-turbo', name: 'Speech 2.8 Turbo', description: '官方最新高速模型，生成更快' },
] as const;

export const OTHER_MODELS = [
  { id: 'speech-2.6-hd', name: 'Speech 2.6 HD', description: '实时表现稳定，适合继续沿用旧项目参数' },
  { id: 'speech-2.6-turbo', name: 'Speech 2.6 Turbo', description: '速度更快，适合追求成本和效率' },
  { id: 'speech-02-hd', name: 'Speech 02 HD', description: '更强节奏与稳定性，高相似度与音质' },
  { id: 'speech-02-turbo', name: 'Speech 02 Turbo', description: '多语言能力更强，整体更稳定' },
] as const;

export const LANGUAGES = [
  { code: 'auto', name: '自动识别' },
  { code: 'Chinese', name: '中文' },
  { code: 'Chinese,Yue', name: '粤语' },
  { code: 'English', name: 'English' },
  { code: 'Arabic', name: 'العربية' },
  { code: 'Portuguese', name: 'Português' },
  { code: 'Turkish', name: 'Türkçe' },
  { code: 'Dutch', name: 'Nederlands' },
  { code: 'Ukrainian', name: 'Українська' },
  { code: 'Vietnamese', name: 'Tiếng Việt' },
  { code: 'Indonesian', name: 'Bahasa Indonesia' },
  { code: 'Japanese', name: '日本語' },
  { code: 'Italian', name: 'Italiano' },
  { code: 'Korean', name: '한국어' },
  { code: 'Thai', name: 'ไทย' },
  { code: 'Polish', name: 'Polski' },
  { code: 'Romanian', name: 'Română' },
  { code: 'Greek', name: 'Ελληνικά' },
  { code: 'Czech', name: 'Čeština' },
  { code: 'Finnish', name: 'Suomi' },
  { code: 'Hindi', name: 'हिन्दी' },
  { code: 'Bulgarian', name: 'Български' },
  { code: 'Danish', name: 'Dansk' },
  { code: 'Hebrew', name: 'עברית' },
  { code: 'Malay', name: 'Bahasa Melayu' },
  { code: 'Persian', name: 'فارسی' },
  { code: 'Slovak', name: 'Slovenčina' },
  { code: 'Swedish', name: 'Svenska' },
  { code: 'Croatian', name: 'Hrvatski' },
  { code: 'Filipino', name: 'Filipino' },
  { code: 'Hungarian', name: 'Magyar' },
  { code: 'Norwegian', name: 'Norsk' },
  { code: 'Slovenian', name: 'Slovenščina' },
  { code: 'Catalan', name: 'Català' },
  { code: 'Nynorsk', name: 'Nynorsk' },
  { code: 'Tamil', name: 'தமிழ்' },
  { code: 'Afrikaans', name: 'Afrikaans' },
  { code: 'Spanish', name: 'Español' },
  { code: 'French', name: 'Français' },
  { code: 'German', name: 'Deutsch' },
  { code: 'Russian', name: 'Русский' },
] as const;
